#!/bin/sh

if [ -z "$(docker compose ps -q egas-plugin)" ]; then
    echo "Unable to connect to docker container. Have you run 'docker compose up -d'?"
else
    docker compose exec egas-plugin sh -c "cd public/plugins/egas && $*"
fi
